main: net.jandie1505.combattest.CombatTest
name: CombatTest
version: 1.0
commands:
  combattest:
    description: CombatTest command
    usage: /combattest <subcommand>
  pay:
    description: Pay another player some points
    usage: /pay <player> <amount>
  menu:
    description: Opens the player menu
    usage: /menu
  combattest-old:
    description: equipment old
    usage: /combattest-old
permissions:
  combattest.admin:
    default: op
    description: admin permission
  combattest.*:
    default: op
    children:
      - combattest.admin
author: jandie1505
api-version: 1.21
softdepend: [SuperVanish,PremiumVanish,CloudNet-Bridge]